import React,{useEffect,useState} from 'react'; import {createRoot} from 'react-dom/client'; import {ShieldCheck,Radio,AlertTriangle,Activity,LockKeyhole,Upload,Play,FileWarning,Network,Database,ChevronRight} from 'lucide-react'; import './style.css';
const API='http://localhost:8000/api';
function Badge({children,kind=''}){return <span className={'badge '+kind}>{children}</span>}
function App(){const [tab,setTab]=useState('Dashboard'); const [stats,setStats]=useState<any>({}); const [alerts,setAlerts]=useState<any[]>([]); const [busy,setBusy]=useState(false); const [last,setLast]=useState<any>(); const [error,setError]=useState(''); const [healthOnline,setHealthOnline]=useState(false);
 async function refresh(){try{setStats(await fetch(API+'/stats').then(r=>r.json()));setAlerts(await fetch(API+'/alerts').then(r=>r.json()))}catch{} }
 useEffect(()=>{if(!['Dashboard','Alert Center','Analytics'].includes(tab))return; refresh();const id=setInterval(refresh,1500);return()=>clearInterval(id)},[tab])
 useEffect(()=>{let active=true;let controller:AbortController|undefined;async function checkHealth(){controller?.abort();controller=new AbortController();const timeout=setTimeout(()=>controller?.abort(),5000);try{const response=await fetch(API+'/health',{signal:controller.signal});if(active)setHealthOnline(response.ok)}catch{if(active)setHealthOnline(false)}finally{clearTimeout(timeout)}}checkHealth();const id=setInterval(checkHealth,5000);return()=>{active=false;controller?.abort();clearInterval(id)}},[])
 async function simulate(s){setBusy(true);setError('');try{const response=await fetch(API+'/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenario:s,chunks:6})});if(!response.ok)throw new Error(`Simulation failed (${response.status})`);const r=await response.json();setLast(r.results?.[r.results.length-1]);await refresh()}catch(exc){setError(exc instanceof Error?exc.message:'Simulation failed')}finally{setBusy(false)}}
 async function upload(e){const file=e.target.files?.[0];if(!file)return;const fd=new FormData();fd.append('file',file);setBusy(true);const r=await fetch(API+'/analyze',{method:'POST',body:fd}).then(x=>x.json());setLast(r);await refresh();setBusy(false)}
 const nav=['Dashboard','Live Analysis Monitor — Prototype','Alert Center','Simulation Lab (Reproducible Demonstration Scenario)','Analytics','Audit Ledger','Architecture','Model'];
 return <div className="app"><aside><div className="brand"><div className="logo"><ShieldCheck/></div><div><b>VoiceShield</b></div></div><div className="nav">{nav.map(n=><button className={tab===n?'active':''} onClick={()=>setTab(n)} key={n}>{n}<ChevronRight size={15}/></button>)}</div><div className="sidebox"><LockKeyhole size={17}/><b>DEFENSIVE MODE</b><p>No outbound calls, identity actions or account changes are performed.</p></div></aside><main><header><div><h1>{tab}</h1><p>Prototype Demonstration — Not Production-Validated</p></div><div className="status"><Badge kind={healthOnline?'green':'red'}>● SYSTEM {healthOnline?'ONLINE':'OFFLINE'}</Badge><Badge>READ-ONLY AUDIO</Badge></div></header>{tab==='Dashboard'&&<Dashboard stats={stats} alerts={alerts} last={last} simulate={simulate} upload={upload} busy={busy}/>} {tab==='Live Analysis Monitor — Prototype'&&<Live last={last}/>} {tab==='Alert Center'&&<Alerts alerts={alerts} refresh={refresh}/>} {tab==='Simulation Lab (Reproducible Demonstration Scenario)'&&<Sim simulate={simulate} busy={busy} last={last} error={error}/>} {tab==='Analytics'&&<Analytics stats={stats} alerts={alerts}/>} {tab==='Audit Ledger'&&<Ledger/>} {tab==='Architecture'&&<Architecture/>} {tab==='Model'&&<Model/>}</main></div>}
function Cards({stats}){return <div className="cards"><Card icon={<Activity/>} t="Audio Analyses" v={stats.total_analyses||0}/><Card icon={<AlertTriangle/>} t="Suspicious" v={stats.suspicious||0}/><Card icon={<FileWarning/>} t="Active Alerts" v={stats.alerts||0}/><Card icon={<ShieldCheck/>} t="Critical" v={stats.critical||0}/><Card icon={<Radio/>} t="Analyses/sec" v={stats.analysis_per_sec||0}/></div>}
function Card(p){return <div className="card"><span>{p.icon}</span><small>{p.t}</small><strong>{p.v}</strong></div>}
function Dashboard({stats,alerts,last,simulate,upload,busy}){return <><div className="hero"><div><div className="eyebrow">TRUST BOUNDARY</div><h2>CAPTURE → ANALYZE → VERIFY → ALERT</h2><p>Only authorized voice/audio data enters the monitoring pipeline. Prevention is a workflow control, not an automated transaction.</p></div><div className="trust"><div><LockKeyhole/> READ-ONLY AUDIO INGEST</div><div><Network/> OUTBOUND ACTIONS: DISABLED</div><div><ShieldCheck/> STEP-UP VERIFICATION AVAILABLE</div></div></div><Cards stats={stats}/><div className="grid2"><section className="panel"><div className="pt"><h3>Quick simulation</h3><span>DEMO / SYNTHETIC DATA</span></div><div className="simgrid">{['NORMAL','CLONED_VOICE','REPLAY','LOW_QUALITY','MIXED_RISK'].map(s=><button disabled={busy} onClick={()=>simulate(s)} className={s==='CLONED_VOICE'?'dangerbtn':''} key={s}><Play size={15}/>{s.replace('_',' ')}</button>)}</div><label className="upload"><Upload size={18}/> Analyze Real WAV<input type="file" accept="audio/wav,.wav" onChange={upload}/></label></section><section className="panel"><div className="pt"><h3>Latest decision</h3><Badge kind={last?.severity==='CRITICAL'?'red':''}>{last?.severity||'NO DATA'}</Badge></div>{last?<div className="decision"><div className="risk">{last.risk_score}<small>/100</small></div><div><b>{last.threat_class}</b><p>Confidence {last.confidence}% · Speaker-Match Evidence {Math.round(last.speaker_match*100)}% · Passive Liveness Indicator {Math.round(last.liveness*100)}%</p></div></div>:<p className="muted">Run a scenario or upload a WAV file.</p>}</section></div><section className="panel"><div className="pt"><h3>Recent alerts</h3><span>{alerts.length} total</span></div><AlertTable alerts={alerts.slice(0,6)}/></section></>}
function AlertTable({alerts}){return <table><thead><tr><th>Alert</th><th>Threat</th><th>Severity</th><th>Confidence</th><th>Risk</th><th>Status</th></tr></thead><tbody>{alerts.map(a=><tr key={a.alert_id}><td className="mono">{a.alert_id}</td><td>{a.threat_class}</td><td><Badge kind={a.severity==='CRITICAL'||a.severity==='HIGH'?'red':''}>{a.severity}</Badge></td><td>{a.confidence}%</td><td><b>{a.risk_score}</b></td><td>{a.status}</td></tr>)}{!alerts.length&&<tr><td colSpan={6} className="empty">No alerts yet.</td></tr>}</tbody></table>}
function Live({last}){return <section className="panel"><div className="pt"><h3>Streaming analysis feed</h3><Badge kind="green">STREAM ONLINE</Badge></div><div className="stream"><div className="streamrow head"><span>TIME</span><span>ANALYSIS ID</span><span>MODEL</span><span>CLONE P</span><span>PASSIVE LIVENESS INDICATOR</span><span>RISK</span></div>{last&&Array.from({length:14},(_,i)=><div className="streamrow" key={i}><span>{new Date((last.timestamp-i*.8)*1000).toLocaleTimeString()}</span><span className="mono">{last.analysis_id.slice(0,12)}…</span><span>DemoRF</span><span>{last.model.clone_probability}</span><span>{last.liveness}</span><span><Badge kind={last.risk_score>60?'red':''}>{last.risk_score}</Badge></span></div>)}{!last&&<div className="empty">Start a simulation to populate the streaming view.</div>}</div></section>}
function Alerts({alerts,refresh}){return <section className="panel"><div className="pt"><h3>Alert center</h3><p>Internal workflow only — status changes are not sent externally.</p></div><AlertTable alerts={alerts}/>{alerts.slice(0,3).map(a=><div className="evidence" key={a.alert_id}><b>{a.alert_id} · WHY WAS THIS FLAGGED?</b>{a.evidence.map((e,i)=><div key={i}><span>{e.feature}</span><strong>{String(e.observed)}</strong><small>{e.reason}</small></div>)}</div>)}</section>}
function Sim({simulate,busy,last,error}){return <section className="panel"><h3>Reproducible Demonstration Scenario</h3><p className="muted">Each scenario generates synthetic WAV samples and sends them through the same feature extraction, ML and risk-fusion path.</p><div className="scenarioCards">{['NORMAL','CLONED_VOICE','REPLAY','LOW_QUALITY','MIXED_RISK'].map((s,i)=><button disabled={busy} onClick={()=>simulate(s)} key={s}><span>0{i+1}</span><b>{s.replace('_',' ')}</b><small>{i===0?'Natural demo speech':i===1?'Synthetic-like voice':'Adversarial condition'}</small></button>)}</div>{busy&&<p className="muted">Running simulation...</p>}{error&&<p className="muted">{error}</p>}{last&&<div className="decision"><div className="risk">{last.risk_score}<small>/100</small></div><div><b>{last.threat_class}</b><p>Confidence {last.confidence}% · Speaker-Match Evidence {Math.round(last.speaker_match*100)}% · Passive Liveness Indicator {Math.round(last.liveness*100)}%</p></div></div>}</section>}
function Analytics({stats,alerts}){let dist=['LOW','MEDIUM','HIGH','CRITICAL'].map(s=>({s,n:alerts.filter(a=>a.severity===s).length}));return <><Cards stats={stats}/><div className="grid2"><section className="panel"><h3>Severity distribution</h3>{dist.map(d=><div className="bar" key={d.s}><span>{d.s}</span><div><i style={{width:`${Math.min(100,d.n*20+2)}%`}}/></div><b>{d.n}</b></div>)}</section><section className="panel"><h3>Pipeline measurements</h3><Metric n="Observed Processing Time" v={(stats.avg_latency_ms||0)+' ms'}/><Metric n="Measured analysis rate" v={(stats.analysis_per_sec||0)+' / sec'}/><Metric n="Ledger integrity" v={stats.ledger_valid?'VALID':'INVALID'}/><Metric n="Data mode" v="DEMO / SYNTHETIC"/></section></div></>}
function Metric({n,v}){return <div className="metric"><span>{n}</span><b>{v}</b></div>}
function Ledger(){const [d,setD]=useState<any>({items:[],valid:true});useEffect(()=>{fetch(API+'/ledger').then(r=>r.json()).then(setD)},[]);return <section className="panel"><div className="pt"><h3>Tamper-evident audit ledger</h3><Badge kind="green">{d.valid?'CHAIN VALID':'CHAIN INVALID'}</Badge></div><p className="muted">Local SHA-256 hash chain for audit integrity. This is not a decentralized blockchain network.</p>{d.items.map((x:any)=><div className="ledger" key={x.hash}><b>#{x.index} {x.event_type}</b><small>{new Date(x.timestamp*1000).toLocaleString()}</small><code>{x.hash}</code></div>)}</section>}
function Architecture(){return <section className="panel architecture"><div className="warning"><LockKeyhole/> NO OUTBOUND ACTIONS · NO CALL PLACEMENT · NO IDENTITY CHANGES</div>{['Authorized audio source','Read-only audio capture','Streaming chunk processor','Acoustic feature extraction','Clone detector + speaker verification + liveness','Risk fusion engine','Prevention policy','Alert center + audit ledger'].map((x,i)=><div className="archrow" key={x}><span>{i+1}</span><b>{x}</b>{i<7&&<ChevronRight/>}</div>)}<h3>Prevention policy</h3><p>If risk exceeds policy threshold, VoiceShield recommends <b>step-up verification</b> and creates an audit alert. It never completes a sensitive action on the user's behalf.</p></section>}
function Model(){return <section className="panel"><h3>Model card</h3><Badge>DEMO / SYNTHETIC</Badge><div className="modelgrid"><Metric n="Demonstration ML Baseline" v="VoiceClone-DemoRF"/><Metric n="Version" v="0.1-demo-synthetic"/><Metric n="Algorithm" v="Random Forest"/><Metric n="Features" v="12 acoustic features"/><Metric n="Validation" v="Synthetic hold-out"/><Metric n="Real-world accuracy" v="NOT CLAIMED"/></div><h3>Limitations</h3><ul><li>Demo distributions are synthetic and do not represent real attack prevalence.</li><li>Robust deployment needs speaker-disjoint, multilingual and codec/replay/TTS/VC evaluation.</li><li>Speaker-Match Evidence and Passive Liveness Indicators in this prototype are risk indicators, not identity proof.</li></ul></section>}
createRoot(document.getElementById('root')!).render(<App/>);
